# ASP.NET Core
- task: DotNetCoreCLI@2
  inputs:
    azureSubscription: 'Pay-As-You-Go(6c241e4d-6fc0-43a4-87c7-a27d9d0d48e0)'
    command: 'build'
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
